#!/usr/bin/env bash
# Install the backup pull on this host, deriving every host-specific value from the
# environment file this repository already keeps.
#
# The pull needs four things this repository deliberately does not carry: an address, two destination paths, and the account to run as.
# The first three are already in ~/.secrets/Blog.<server>.<environment>.env under the same names the pull itself uses, so this copies them rather than translating them, and the account is whoever runs this.
#
# There is no name mapping here, because both sides spell every shared value the same way.
# Keep it that way: a translation table is a thing to get wrong every time one side changes.
#
# Usage: ops/install.sh [--check] [--force]
#   --check   validate and print what would be written, touch nothing, need no root
#   --force   overwrite an existing config file whose contents differ
#
# RUN IT AS THE ACCOUNT THAT WILL OWN THE BACKUP, not under sudo. That account's name and
# its SSH key are what the unit is built around, and running this under sudo would record
# root. Individual privileged steps call sudo themselves.
set -euo pipefail

CHECK=0
FORCE=0
while [[ $# -gt 0 ]]; do
	case "$1" in
	--check)
		CHECK=1
		shift
		;;
	--force)
		FORCE=1
		shift
		;;
	-h | --help)
		sed -n '2,22p' "$0"
		exit 0
		;;
	*)
		printf 'ERROR: unknown argument %s\n' "$1" >&2
		exit 1
		;;
	esac
done

die() {
	printf 'ERROR: %s\n' "$*" >&2
	exit 1
}
note() { printf '  %s\n' "$*"; }

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
ENV_FILE=${ENV_FILE:-$HOME/.secrets/Blog.local.production.env}
# The same rule deploy/make-release.sh applies, because the two read the same files and a name that means different things depending on where you stood is worse here: this one installs.
# A relative name resolves against ~/.secrets, so it means the same from any directory, and traversal is refused rather than resolved, since a relative name is meant to reach ~/.secrets.
case "$ENV_FILE" in
/*) ;;
*..*) die "ENV_FILE must not traverse: $ENV_FILE" ;;
*) ENV_FILE="$HOME/.secrets/$ENV_FILE" ;;
esac

[[ $EUID -ne 0 ]] || die "do not run this under sudo -- run it as the account that will own the backup; it calls sudo for the steps that need it"
[[ -f $ENV_FILE ]] || die "$ENV_FILE does not exist (ENV_FILE overrides which file is read)"

# Sourced the same way every other script here reads it, so a value set by hand in the
# caller's shell does not quietly win over the file that is supposed to be authoritative.
set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

[[ -n ${VPS_SSH_HOST:-} ]] || die "VPS_SSH_HOST is not set in $ENV_FILE"
[[ -n ${BACKUP_ARCHIVE_ROOT:-} ]] || die "BACKUP_ARCHIVE_ROOT is not set in $ENV_FILE"
[[ -n ${LOG_ARCHIVE_ROOT:-} ]] || die "LOG_ARCHIVE_ROOT is not set in $ENV_FILE"

ACCOUNT=$(id -un)

# The nearest existing ancestor of the destination, which is what both the group and the
# mount are read from. The destination itself may not exist on a first install.
ANCESTOR=$BACKUP_ARCHIVE_ROOT
while [[ ! -e $ANCESTOR && $ANCESTOR != / ]]; do ANCESTOR=$(dirname "$ANCESTOR"); done

# The group comes from the destination rather than from `id -gn`, which is the wrong answer
# whenever the account's primary group is not the group that owns the backup tree. Group=
# sets the process's primary group, so getting it from the user would create files the
# existing tree's group cannot read, and only on the paths where a setgid bit does not
# already override it -- so it would half work, which is worse than failing.
GROUP=$(stat -c %G "$ANCESTOR")

# The mount the destination sits on, resolved rather than guessed, because RequiresMountsFor
# has to name the mount point and not the directory below it.
MOUNT=$(findmnt -no TARGET --target "$ANCESTOR" 2>/dev/null) ||
	die "cannot resolve the mount holding $BACKUP_ARCHIVE_ROOT"

VPS_TRAEFIK_ARCHIVE=${VPS_TRAEFIK_LOG_ARCHIVE:-/var/log/traefik/archive}

# A display value only, built without the \~ parameter-expansion escape, since bash versions differ on whether that yields a literal backslash, and this is what an operator reads to trust the source file.
ENV_FILE_DISPLAY=$ENV_FILE
case "$ENV_FILE_DISPLAY" in
"$HOME"/*)
	# shellcheck disable=SC2088 # Literal display text, deliberately not expanded.
	ENV_FILE_DISPLAY="~/${ENV_FILE_DISPLAY#"$HOME"/}"
	;;
esac

printf '=== derived from %s\n' "$ENV_FILE_DISPLAY"
note "VPS_SSH_HOST         $VPS_SSH_HOST"
note "BACKUP_ARCHIVE_ROOT  $BACKUP_ARCHIVE_ROOT"
note "LOG_ARCHIVE_ROOT     $LOG_ARCHIVE_ROOT"
note "VPS_TRAEFIK_LOG_ARC. $VPS_TRAEFIK_ARCHIVE"
note "account              $ACCOUNT:$GROUP"
note "mount                $MOUNT"

ENV_DEST=/etc/vps-backup-pull.env
DROPIN_DIR=/etc/systemd/system/vps-backup-pull.service.d
DROPIN_DEST=$DROPIN_DIR/local.conf

ENV_BODY=$(
	cat <<EOF
# Generated by ops/install.sh from $ENV_FILE_DISPLAY. Re-run that rather than editing
# here, or this copy and the one the log review reads stop agreeing and nothing reports it.
VPS_SSH_HOST=$VPS_SSH_HOST
VPS_ARCHIVE_DIR=${VPS_ARCHIVE_DIR:-/var/backups/pangolin}
VPS_TRAEFIK_LOG_ARCHIVE=$VPS_TRAEFIK_ARCHIVE
VPS_BLOG_LOG_DIR=${VPS_BLOG_LOG_DIR:-/var/log/blog/legacy}
BACKUP_ARCHIVE_ROOT=$BACKUP_ARCHIVE_ROOT
LOG_ARCHIVE_ROOT=$LOG_ARCHIVE_ROOT
SSH_OPTS="-o ConnectTimeout=15 -o BatchMode=yes"
EOF
)

DROPIN_BODY=$(
	cat <<EOF
# Generated by ops/install.sh. The three settings here name one machine, which is why the
# unit in git does not carry them.
[Unit]
RequiresMountsFor=$MOUNT

[Service]
User=$ACCOUNT
Group=$GROUP
EOF
)

# Reported before anything is written, because "already correct" and "about to change" are
# the two states worth telling apart and an installer that prints neither is one you have to
# read the filesystem to trust.
# Existence is testable without root because /etc is readable; the contents are not, since
# the env file is mode 600. So comparison is attempted with `sudo -n` and its absence is
# reported as unknown rather than silently treated as "no change" -- an installer that says
# "already correct" because it could not look is the failure this whole file is written
# against.
changed=0
for pair in "$ENV_DEST|$ENV_BODY" "$DROPIN_DEST|$DROPIN_BODY"; do
	path=${pair%%|*}
	body=${pair#*|}
	if [[ ! -e $path ]]; then
		printf '=== %s: will be created\n' "$path"
		changed=1
	elif ! sudo -n true 2>/dev/null; then
		printf '=== %s: exists, contents need root to compare\n' "$path"
		changed=1
	elif printf '%s\n' "$body" | sudo -n diff -q - "$path" >/dev/null 2>&1; then
		printf '=== %s: already correct\n' "$path"
	else
		printf '=== %s: differs\n' "$path"
		printf '%s\n' "$body" | sudo -n diff -u "$path" - || true
		# --force is an install-path guard, not a reporting one. --check exists to show what
		# would happen, so stopping at the first differing file would hide the second one and
		# the reachability test behind it.
		if [[ $CHECK -eq 0 && $FORCE -eq 0 ]]; then
			die "$path exists with different contents -- re-run with --force to replace it"
		fi
		changed=1
	fi
done

if [[ $CHECK -eq 1 ]]; then
	printf '\n=== %s would contain\n' "$ENV_DEST"
	printf '%s\n' "$ENV_BODY" | sed 's/^/  /'
	printf '\n=== %s would contain\n' "$DROPIN_DEST"
	printf '%s\n' "$DROPIN_BODY" | sed 's/^/  /'
	printf '\n=== check only -- nothing written\n'
	printf '=== verifying the VPS is reachable as %s\n' "$ACCOUNT"
	# if/else rather than `A && B || C`, which runs C when B fails as well as when A does.
	# shellcheck disable=SC2086
	if ssh ${SSH_OPTS:--o ConnectTimeout=15 -o BatchMode=yes} "$VPS_SSH_HOST" true; then
		printf '  reachable\n'
	else
		die "cannot reach $VPS_SSH_HOST over SSH as $ACCOUNT (key auth only)"
	fi
	exit 0
fi

printf '=== installing\n'
sudo install -m 755 "$REPO/ops/vps-backup-pull" /usr/local/bin/vps-backup-pull
sudo install -m 644 "$REPO/ops/vps-backup-pull.service" "$REPO/ops/vps-backup-pull.timer" \
	/etc/systemd/system/
printf '%s\n' "$ENV_BODY" | sudo install -m 600 /dev/stdin "$ENV_DEST"
sudo mkdir -p "$DROPIN_DIR"
printf '%s\n' "$DROPIN_BODY" | sudo install -m 644 /dev/stdin "$DROPIN_DEST"
sudo systemctl daemon-reload
sudo systemctl enable --now vps-backup-pull.timer

printf '=== verifying the installed copy, without writing a journal entry\n'
# --dry-run rather than starting the service, because a service record is the evidence that
# the timer fired, and manufacturing one here would spend that evidence to prove the install.
/usr/local/bin/vps-backup-pull --dry-run >/dev/null ||
	die "the installed script failed its dry run -- $ENV_DEST or the drop-in is wrong"
printf '  dry run clean\n'
systemctl list-timers vps-backup-pull.timer --all --no-pager
if [[ $changed -eq 1 ]]; then
	printf '=== done\n'
else
	printf '=== done -- configuration was already correct\n'
fi
