#!/usr/bin/env bash
# Install the backup pull on this host, deriving every host-specific value from the
# environment file this repository already keeps.
#
# The pull needs three things this repository deliberately does not carry: an address, two
# destination paths, and the account to run as. All three are already known here --
# secrets/<server>.<environment>.env holds the first three under the names the log review
# uses, and the account is whoever runs this. So they are derived rather than retyped, and
# the two vocabularies OPERATIONS.md describes cannot drift, because one is generated from
# the other.
#
#   VPS_SSH_HOST            -> VPS_HOST
#   BACKUP_ARCHIVE_ROOT     -> DEST
#   LOG_ARCHIVE_ROOT        -> LOG_DEST
#   VPS_TRAEFIK_LOG_ARCHIVE -> REMOTE_TRAEFIK_LOG_DIR
#
# Usage: ops/install.sh [--check] [--force]
#   --check   validate and print what would be written, touch nothing, need no root
#   --force   overwrite an existing config file whose contents differ
#
# RUN IT AS THE ACCOUNT THAT WILL OWN THE BACKUP, not under sudo. That account's name and
# its SSH key are what the unit is built around, and running this under sudo would record
# root. Individual privileged steps call sudo themselves.
set -euo pipefail

CHECK=0; FORCE=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check) CHECK=1; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) sed -n '2,22p' "$0"; exit 0 ;;
    *) printf 'ERROR: unknown argument %s\n' "$1" >&2; exit 1 ;;
  esac
done

die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
note() { printf '  %s\n' "$*"; }

REPO=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
ENV_FILE=${ENV_FILE:-$REPO/secrets/local.production.env}

[[ $EUID -ne 0 ]] || die "do not run this under sudo -- run it as the account that will own the backup; it calls sudo for the steps that need it"
[[ -f $ENV_FILE ]] || die "$ENV_FILE does not exist (ENV_FILE overrides which file is read)"

# Sourced the same way every other script here reads it, so a value set by hand in the
# caller's shell does not quietly win over the file that is supposed to be authoritative.
set -a
# shellcheck disable=SC1090
. "$ENV_FILE"
set +a

[[ -n ${VPS_SSH_HOST:-} ]]        || die "VPS_SSH_HOST is not set in $ENV_FILE"
[[ -n ${BACKUP_ARCHIVE_ROOT:-} ]] || die "BACKUP_ARCHIVE_ROOT is not set in $ENV_FILE"
[[ -n ${LOG_ARCHIVE_ROOT:-} ]]    || die "LOG_ARCHIVE_ROOT is not set in $ENV_FILE"

ACCOUNT=$(id -un)

# The nearest existing ancestor of the destination, which is what both the group and the
# mount are read from. The destination itself may not exist on a first install.
ANCESTOR=$BACKUP_ARCHIVE_ROOT
while [[ ! -e $ANCESTOR && $ANCESTOR != / ]]; do ANCESTOR=$(dirname "$ANCESTOR"); done

# The group comes from the destination rather than from `id -gn`, which is the wrong answer
# whenever the account's primary group is not the group that owns the backup tree. Group=
# sets the process's primary group, so getting it from the user would create files the
# existing tree's group cannot read, and only on the paths where a setgid bit does not
# already override it -- so it would half work, which is worse than failing.
GROUP=$(stat -c %G "$ANCESTOR")

# The mount the destination sits on, resolved rather than guessed, because RequiresMountsFor
# has to name the mount point and not the directory below it.
MOUNT=$(findmnt -no TARGET --target "$ANCESTOR" 2>/dev/null) \
  || die "cannot resolve the mount holding $BACKUP_ARCHIVE_ROOT"

REMOTE_TRAEFIK=${VPS_TRAEFIK_LOG_ARCHIVE:-/var/log/traefik/archive}

printf '=== derived from %s\n' "${ENV_FILE#"$REPO"/}"
note "VPS_HOST    $VPS_SSH_HOST"
note "DEST        $BACKUP_ARCHIVE_ROOT"
note "LOG_DEST    $LOG_ARCHIVE_ROOT"
note "remote logs $REMOTE_TRAEFIK"
note "account     $ACCOUNT:$GROUP"
note "mount       $MOUNT"

ENV_DEST=/etc/vps-backup-pull.env
DROPIN_DIR=/etc/systemd/system/vps-backup-pull.service.d
DROPIN_DEST=$DROPIN_DIR/local.conf

ENV_BODY=$(cat <<EOF
# Generated by ops/install.sh from ${ENV_FILE#"$REPO"/}. Re-run that rather than editing
# here, or the two copies of these paths stop agreeing and nothing reports it.
VPS_HOST=$VPS_SSH_HOST
DEST=$BACKUP_ARCHIVE_ROOT
LOG_DEST=$LOG_ARCHIVE_ROOT
REMOTE_ARCHIVE_DIR=${REMOTE_ARCHIVE_DIR:-/var/backups/pangolin}
REMOTE_TRAEFIK_LOG_DIR=$REMOTE_TRAEFIK
REMOTE_BLOG_LOG_DIR=${REMOTE_BLOG_LOG_DIR:-/var/log/blog/legacy}
SSH_OPTS=-o ConnectTimeout=15 -o BatchMode=yes
EOF
)

DROPIN_BODY=$(cat <<EOF
# Generated by ops/install.sh. The three settings here name one machine, which is why the
# unit in git does not carry them.
[Unit]
RequiresMountsFor=$MOUNT

[Service]
User=$ACCOUNT
Group=$GROUP
EOF
)

# Reported before anything is written, because "already correct" and "about to change" are
# the two states worth telling apart and an installer that prints neither is one you have to
# read the filesystem to trust.
# Existence is testable without root because /etc is readable; the contents are not, since
# the env file is mode 600. So comparison is attempted with `sudo -n` and its absence is
# reported as unknown rather than silently treated as "no change" -- an installer that says
# "already correct" because it could not look is the failure this whole file is written
# against.
changed=0
for pair in "$ENV_DEST|$ENV_BODY" "$DROPIN_DEST|$DROPIN_BODY"; do
  path=${pair%%|*}; body=${pair#*|}
  if [[ ! -e $path ]]; then
    printf '=== %s: will be created\n' "$path"; changed=1
  elif ! sudo -n true 2>/dev/null; then
    printf '=== %s: exists, contents need root to compare\n' "$path"; changed=1
  elif printf '%s\n' "$body" | sudo -n diff -q - "$path" >/dev/null 2>&1; then
    printf '=== %s: already correct\n' "$path"
  else
    printf '=== %s: differs\n' "$path"
    printf '%s\n' "$body" | sudo -n diff -u "$path" - || true
    [[ $FORCE -eq 1 ]] || die "$path exists with different contents -- re-run with --force to replace it"
    changed=1
  fi
done

if [[ $CHECK -eq 1 ]]; then
  printf '\n=== %s would contain\n' "$ENV_DEST"
  printf '%s\n' "$ENV_BODY" | sed 's/^/  /'
  printf '\n=== %s would contain\n' "$DROPIN_DEST"
  printf '%s\n' "$DROPIN_BODY" | sed 's/^/  /'
  printf '\n=== check only -- nothing written\n'
  printf '=== verifying the VPS is reachable as %s\n' "$ACCOUNT"
  # shellcheck disable=SC2086
  ssh ${SSH_OPTS:--o ConnectTimeout=15 -o BatchMode=yes} "$VPS_SSH_HOST" true \
    && printf '  reachable\n' \
    || die "cannot reach $VPS_SSH_HOST over SSH as $ACCOUNT (key auth only)"
  exit 0
fi

printf '=== installing\n'
sudo install -m 755 "$REPO/ops/vps-backup-pull" /usr/local/bin/vps-backup-pull
sudo install -m 644 "$REPO/ops/vps-backup-pull.service" "$REPO/ops/vps-backup-pull.timer" \
  /etc/systemd/system/
printf '%s\n' "$ENV_BODY" | sudo install -m 600 /dev/stdin "$ENV_DEST"
sudo mkdir -p "$DROPIN_DIR"
printf '%s\n' "$DROPIN_BODY" | sudo install -m 644 /dev/stdin "$DROPIN_DEST"
sudo systemctl daemon-reload
sudo systemctl enable --now vps-backup-pull.timer

printf '=== verifying the installed copy, without writing a journal entry\n'
# --dry-run rather than starting the service, because a service record is the evidence that
# the timer fired, and manufacturing one here would spend that evidence to prove the install.
/usr/local/bin/vps-backup-pull --dry-run >/dev/null \
  || die "the installed script failed its dry run -- $ENV_DEST or the drop-in is wrong"
printf '  dry run clean\n'
systemctl list-timers vps-backup-pull.timer --all --no-pager
if [[ $changed -eq 1 ]]; then
  printf '=== done\n'
else
  printf '=== done -- configuration was already correct\n'
fi
